export enum CMD {
  InitGraph = 'InitGraph',
  Clear = 'Clear',
  CanvasTransform = 'CanvasTransform',
  ZoomToFit = 'ZoomToFit',
  CenterElement = 'CenterElement',
  CreateNode = 'CreateNode',
  UpdateNode = 'UpdateNode',
  NodeDragEnd = 'NodeDragEnd',
  CreateEdge = 'CreateEdge',
  UpdateEdge = 'UpdateEdge',
  DeleteNode = 'DeleteNode',
  DeleteEdge = 'DeleteEdge',
  HoverElement = 'HoverElement',
  ClickNode = 'ClickNode',
  SelectNode = 'SelectNode',
  DeselectNode = 'DeselectNode',
  ClickEdge = 'ClickEdge',
  SelectEdge = 'SelectEdge',
  DeselectEdge = 'DeselectEdge',
  RecalculateGraphLayout = 'RecalculateGraphLayout',
  UpdateWorkspaceConfig = 'UpdateWorkspaceConfig',
  DragModeChange = 'DragModeChange',
  MouseMove = 'MouseMove',
  Undo = 'Undo',
  Redo = 'Redo',
}